/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
public class QuanLyKyHocView extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKyHocView
     */
    public QuanLyKyHocView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneCustom2 = new view.swing.TabbedPaneCustom();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAddKiHoc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIDKiHoc = new javax.swing.JTextField();
        txtTenKyHoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamHoc = new javax.swing.JTextField();
        btnUpdateKiHoc = new javax.swing.JButton();
        btnResetKiHoc = new javax.swing.JButton();
        btnDeleteKiHoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbKiHoc = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1293, 747));

        tabbedPaneCustom2.setSelectedColor(new java.awt.Color(58, 73, 87));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("QUẢN LÍ KỲ HỌC");

        btnAddKiHoc.setText("ADD");
        btnAddKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKiHocActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID Kỳ Học");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên Kỳ Học");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Năm Học");

        btnUpdateKiHoc.setText("UPDATE");
        btnUpdateKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKiHocActionPerformed(evt);
            }
        });

        btnResetKiHoc.setText("RESET");

        btnDeleteKiHoc.setText("DELETE");
        btnDeleteKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKiHocActionPerformed(evt);
            }
        });

        jtbKiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbKiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbKiHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbKiHoc);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnAddKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnUpdateKiHoc)
                        .addGap(29, 29, 29)
                        .addComponent(btnDeleteKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(4, 4, 4))))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKyHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(534, 534, 534)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIDKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenKyHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnResetKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        tabbedPaneCustom2.addTab("Chức Năng", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1310, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );

        tabbedPaneCustom2.addTab("Tìm Kiếm", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPaneCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 1315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCustom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbKiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbKiHocMouseClicked
//        index = jtbKiHoc.getSelectedRow();
//        showData(index);
    }//GEN-LAST:event_jtbKiHocMouseClicked

    private void btnAddKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKiHocActionPerformed
//        if(validateKiHoc()){
//            KiHoc kh = this.readForm();
//            if(khsv.checkTrungID(kh.getId())){
//                JOptionPane.showMessageDialog(this, "Lỗi Trùng mã");
//                return;
//            }
//            if(khsv.AddKiHoc(kh)!= 0){
//                JOptionPane.showMessageDialog(this, "Thêm thành công");
//                fillTable(khsv.getAll());
//            }else{
//                JOptionPane.showMessageDialog(this, "Thêm thất bại");
//                return;
//            }
//        }
    }//GEN-LAST:event_btnAddKiHocActionPerformed

    private void btnDeleteKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKiHocActionPerformed
//        index = jtbKiHoc.getSelectedRow();
//        String id = jtbKiHoc.getValueAt(index, 0).toString();
//        if(khsv.deleteKiHoc(id) != 0){
//            JOptionPane.showMessageDialog(this, "Xóa Thành công");
//            txtNamHoc.setText("");
//            txtIDKiHoc.setText("");
//            txtTenKyHoc.setText("");
//            fillTable(khsv.getAll());
//        }else{
//            JOptionPane.showMessageDialog(this, "Xóa thất bại");
//        }
    }//GEN-LAST:event_btnDeleteKiHocActionPerformed

    private void btnUpdateKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKiHocActionPerformed
//        if(validateKiHoc()){
//            KiHoc kh = this.readForm();
//            index = jtbKiHoc.getSelectedRow();
//            String id = jtbKiHoc.getValueAt(index, 0).toString();
//            System.out.println(""+id);
//            //            if(khsv.checkTrungID(kh.getId())){
//                //                JOptionPane.showMessageDialog(this, "Lỗi Trùng mã");
//                //                return;
//                //            }
//            if(khsv.Update(kh, id) != 0){
//                JOptionPane.showMessageDialog(this, "Update thành công");
//                fillTable(khsv.getAll());
//            }else{
//                JOptionPane.showMessageDialog(this, "Update Thất bại");
//            }
//        }
    }//GEN-LAST:event_btnUpdateKiHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddKiHoc;
    private javax.swing.JButton btnDeleteKiHoc;
    private javax.swing.JButton btnResetKiHoc;
    private javax.swing.JButton btnUpdateKiHoc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbKiHoc;
    private view.swing.TabbedPaneCustom tabbedPaneCustom2;
    private javax.swing.JTextField txtIDKiHoc;
    private javax.swing.JTextField txtNamHoc;
    private javax.swing.JTextField txtTenKyHoc;
    // End of variables declaration//GEN-END:variables
}
