/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KiHoc;
import service.KiHocService;

/**
 *
 * @author long0
 */
public class QuanLiSinhVienFrame extends javax.swing.JFrame {

    DefaultTableModel model;
    KiHocService khsv = new KiHocService();
    private int index = -1; 

    /**
     * Creates new form QuanLiSinhVienFrame
     */
    public QuanLiSinhVienFrame() {
        initComponents();
        setTable();
        this.fillTable(khsv.getAll());
    }

    public void setTable() {
        model = (DefaultTableModel) jtbKiHoc.getModel();
        Object[] listTable = {"ID", "Tên Kỳ Học", "Năm Học"};
        model.setColumnIdentifiers(listTable);
        jtbKiHoc.setModel(model);
    }

    public void fillTable(List<KiHoc> list) {
        model = (DefaultTableModel) jtbKiHoc.getModel();
        model.setRowCount(0);
        for (KiHoc kiHoc : list) {
            model.addRow(kiHoc.toDataRow());
        }
    }

    public void showData(int index) {
        KiHoc kh = khsv.getAll().get(index);
        txtIDKiHoc.setText(kh.getId());
        txtTenKyHoc.setText(kh.getTenKyHoc());
        txtNamHoc.setText(String.valueOf(kh.getNamHoc()));
    }

    public boolean validateKiHoc() {
        if (txtIDKiHoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID không được để trống", "Error", 2);
            return false;
        }
        if (txtTenKyHoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên kì học không được để trống", "Error", 2);
            return false;
        }

        if (txtNamHoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên kì học không được để trống", "Error", 2);
            return false;
        } else {
            try {
                int kyHoc = Integer.parseInt(txtNamHoc.getText());
                if (Integer.parseInt(txtNamHoc.getText()) < 0 || Integer.parseInt(txtNamHoc.getText()) > 2023) {
                    JOptionPane.showMessageDialog(this, "Lỗi dữ liệu năm học");
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi dữ liệu kì học");
                return false;
            }

        }
        return true;
    }

    KiHoc readForm() {
        String id = txtIDKiHoc.getText();
        String tenKiHoc = txtTenKyHoc.getText();
        int namHoc = Integer.parseInt(txtNamHoc.getText());
        return new KiHoc(id, tenKiHoc, namHoc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDKiHoc = new javax.swing.JTextField();
        txtTenKyHoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamHoc = new javax.swing.JTextField();
        btnUpdateKiHoc = new javax.swing.JButton();
        btnResetKiHoc = new javax.swing.JButton();
        btnDeleteKiHoc = new javax.swing.JButton();
        btnAddKiHoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbKiHoc = new javax.swing.JTable();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setToolTipText("");

        jPanel2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jPanel2ComponentAdded(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("QUẢN LÍ KỲ HỌC");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID Kỳ Học");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên Kỳ Học");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Năm Học");

        btnUpdateKiHoc.setText("UPDATE");
        btnUpdateKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKiHocActionPerformed(evt);
            }
        });

        btnResetKiHoc.setText("RESET");

        btnDeleteKiHoc.setText("DELETE");
        btnDeleteKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKiHocActionPerformed(evt);
            }
        });

        btnAddKiHoc.setText("ADD");
        btnAddKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKiHocActionPerformed(evt);
            }
        });

        jtbKiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbKiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbKiHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbKiHoc);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(4, 4, 4))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAddKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenKyHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnUpdateKiHoc)
                                .addGap(29, 29, 29)
                                .addComponent(btnDeleteKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResetKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenKyHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Quản Lí Kì Hoc", jPanel1);

        jTabbedPane1.addTab("Kỳ Học", jTabbedPane6);
        jTabbedPane6.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Lớp", jTabbedPane7);
        jTabbedPane1.addTab("Điểm", jTabbedPane3);
        jTabbedPane1.addTab("Sinh Viên", jTabbedPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKiHocActionPerformed
        if(validateKiHoc()){
            KiHoc kh = this.readForm();
            if(khsv.checkTrungID(kh.getId())){
                JOptionPane.showMessageDialog(this, "Lỗi Trùng mã");
                return;
            }
            if(khsv.add(kh)!= 0){
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                fillTable(khsv.getAll());
            }else{
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                return;
            }
        }
    }//GEN-LAST:event_btnAddKiHocActionPerformed

    private void jPanel2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentAdded

    private void jtbKiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbKiHocMouseClicked
      index = jtbKiHoc.getSelectedRow();
        showData(index);
    }//GEN-LAST:event_jtbKiHocMouseClicked

    private void btnUpdateKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKiHocActionPerformed
        if(validateKiHoc()){
            KiHoc kh = this.readForm();
            index = jtbKiHoc.getSelectedRow();
            String id = jtbKiHoc.getValueAt(index, 0).toString();
            System.out.println(""+id);
//            if(khsv.checkTrungID(kh.getId())){
//                JOptionPane.showMessageDialog(this, "Lỗi Trùng mã");
//                return;
//            }
            if(khsv.update(kh, id) != 0){
                JOptionPane.showMessageDialog(this, "Update thành công");
                fillTable(khsv.getAll());
            }else{
                 JOptionPane.showMessageDialog(this, "Update Thất bại");
            }
        }
    }//GEN-LAST:event_btnUpdateKiHocActionPerformed

    private void btnDeleteKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKiHocActionPerformed
        index = jtbKiHoc.getSelectedRow();
        String id = jtbKiHoc.getValueAt(index, 0).toString();
        if(khsv.deleteKiHoc(id) != 0){
            JOptionPane.showMessageDialog(this, "Xóa Thành công");
            txtNamHoc.setText("");
            txtIDKiHoc.setText("");
            txtTenKyHoc.setText("");
            fillTable(khsv.getAll());
        }else{
            JOptionPane.showMessageDialog(this, "Xóa thất bại");
        }
    }//GEN-LAST:event_btnDeleteKiHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiSinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiSinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiSinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiSinhVienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiSinhVienFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddKiHoc;
    private javax.swing.JButton btnDeleteKiHoc;
    private javax.swing.JButton btnResetKiHoc;
    private javax.swing.JButton btnUpdateKiHoc;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTable jtbKiHoc;
    private javax.swing.JTextField txtIDKiHoc;
    private javax.swing.JTextField txtNamHoc;
    private javax.swing.JTextField txtTenKyHoc;
    // End of variables declaration//GEN-END:variables
}
