/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Admin
 */
public class QuanLyKyHocView extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyKyHocView
     */
    public QuanLyKyHocView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnAddKiHoc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIDKiHoc = new javax.swing.JTextField();
        txtTenKyHoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNamHoc = new javax.swing.JTextField();
        btnUpdateKiHoc = new javax.swing.JButton();
        btnResetKiHoc = new javax.swing.JButton();
        btnDeleteKiHoc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbKiHoc = new javax.swing.JTable();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("QUẢN LÍ KỲ HỌC");

        btnAddKiHoc.setText("ADD");
        btnAddKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKiHocActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID Kỳ Học");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tên Kỳ Học");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Năm Học");

        btnUpdateKiHoc.setText("UPDATE");
        btnUpdateKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateKiHocActionPerformed(evt);
            }
        });

        btnResetKiHoc.setText("RESET");

        btnDeleteKiHoc.setText("DELETE");
        btnDeleteKiHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKiHocActionPerformed(evt);
            }
        });

        jtbKiHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbKiHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbKiHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbKiHoc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(441, 441, 441))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(4, 4, 4))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnUpdateKiHoc)
                                .addGap(29, 29, 29)
                                .addComponent(btnDeleteKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResetKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenKyHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(298, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenKyHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNamHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetKiHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtbKiHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbKiHocMouseClicked
//        index = jtbKiHoc.getSelectedRow();
//        showData(index);
    }//GEN-LAST:event_jtbKiHocMouseClicked

    private void btnAddKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKiHocActionPerformed
//        if(validateKiHoc()){
//            KiHoc kh = this.readForm();
//            if(khsv.checkTrungID(kh.getId())){
//                JOptionPane.showMessageDialog(this, "Lỗi Trùng mã");
//                return;
//            }
//            if(khsv.AddKiHoc(kh)!= 0){
//                JOptionPane.showMessageDialog(this, "Thêm thành công");
//                fillTable(khsv.getAll());
//            }else{
//                JOptionPane.showMessageDialog(this, "Thêm thất bại");
//                return;
//            }
//        }
    }//GEN-LAST:event_btnAddKiHocActionPerformed

    private void btnDeleteKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKiHocActionPerformed
//        index = jtbKiHoc.getSelectedRow();
//        String id = jtbKiHoc.getValueAt(index, 0).toString();
//        if(khsv.deleteKiHoc(id) != 0){
//            JOptionPane.showMessageDialog(this, "Xóa Thành công");
//            txtNamHoc.setText("");
//            txtIDKiHoc.setText("");
//            txtTenKyHoc.setText("");
//            fillTable(khsv.getAll());
//        }else{
//            JOptionPane.showMessageDialog(this, "Xóa thất bại");
//        }
    }//GEN-LAST:event_btnDeleteKiHocActionPerformed

    private void btnUpdateKiHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateKiHocActionPerformed
//        if(validateKiHoc()){
//            KiHoc kh = this.readForm();
//            index = jtbKiHoc.getSelectedRow();
//            String id = jtbKiHoc.getValueAt(index, 0).toString();
//            System.out.println(""+id);
//            //            if(khsv.checkTrungID(kh.getId())){
//                //                JOptionPane.showMessageDialog(this, "Lỗi Trùng mã");
//                //                return;
//                //            }
//            if(khsv.Update(kh, id) != 0){
//                JOptionPane.showMessageDialog(this, "Update thành công");
//                fillTable(khsv.getAll());
//            }else{
//                JOptionPane.showMessageDialog(this, "Update Thất bại");
//            }
//        }
    }//GEN-LAST:event_btnUpdateKiHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddKiHoc;
    private javax.swing.JButton btnDeleteKiHoc;
    private javax.swing.JButton btnResetKiHoc;
    private javax.swing.JButton btnUpdateKiHoc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbKiHoc;
    private javax.swing.JTextField txtIDKiHoc;
    private javax.swing.JTextField txtNamHoc;
    private javax.swing.JTextField txtTenKyHoc;
    // End of variables declaration//GEN-END:variables
}
